import React from 'react';
import Head from 'next/head';
import Row from '../../general-styles/Row';
import RowContainer from '../../general-styles/RowContainer';

// import useDimensions from '../custom-design-hooks/useDimensions';

export default function Home() {
  // const width = useDimensions('resize');
  // console.log('Inside products page');
  return (
    <React.Fragment>
      <Head>
        <title>TWS Framework </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row color='#848587'>
        <RowContainer displayOption='grid-center'>
          {/* <section> */}
          <div className='col-span-5'>
            <h1>Main content area left column</h1>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
          </div>

          <div className='col-span-7'>
            <h1>Main content area right column</h1>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
          </div>
          {/* </section> */}
        </RowContainer>
      </Row>

      <Row color='#facf57'>
        <RowContainer displayOption='grid-center'>
          <div className='col-span-12'>
            <h1>This is the products page</h1>
          </div>
        </RowContainer>
      </Row>
    </React.Fragment>
  );
}
