import React from 'react';
import Head from 'next/head';
import Row from '../../general-styles/Row';
import RowContainer from '../../general-styles/RowContainer';

import Img from '../../components/Image/Img';
import Image from 'next/image';
import { useRouter } from 'next/router';

// import useDimensions from '../custom-design-hooks/useDimensions';

export default function Posts() {
  // const width = useDimensions('resize');
  const router = useRouter();
  console.log(router.query);
  return (
    <React.Fragment>
      <Head>
        <title>TWS Framework </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Row color='#facf57'>
        <RowContainer displayOption='grid-center'>
          <div className='col-span-12 lg:col-span-6'>
            <h1>This is the Blogs-slug page</h1>
          </div>
        </RowContainer>
      </Row>
    </React.Fragment>
  );
}
