import React from 'react';
import Head from 'next/head';
import Row from '../../general-styles/Row';
import RowContainer from '../../general-styles/RowContainer';
import RowFluid from '../../general-styles/RowFluid';
import axios from 'axios';

import Img from '../../components/Image/Img';
import Image from 'next/image';

// import useDimensions from '../custom-design-hooks/useDimensions';

export default function Posts(props) {
  // console.log(props.data.content);
  // const width = useDimensions('resize');
  console.log('Inside Posts page');
  return (
    <React.Fragment>
      <Head>
        <title>TWS Framework </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row color='#facf57'>
        <RowContainer displayOption='grid-center'>
          <div className='col-span-12'>
            <h1>This is the Blogs page</h1>
            <a href={props.data.link} target='blank'>
              Post 1 Link
            </a>
          </div>
        </RowContainer>
      </Row>
      <Row>
        <div className='w-full bg-red-500'>
          <div className='w-3/5 bg-blue-400 mx-auto'>
            <div
              className='tws_post_body'
              dangerouslySetInnerHTML={{
                __html: props.data.content.rendered,
              }}
            />
          </div>
        </div>
      </Row>
    </React.Fragment>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get(
    'http://headless-cms.test/wp-json/wp/v2/posts/30'
  );
  // const data = JSON.parse(postsData);
  console.log(data);
  return {
    props: {
      data: data,
    },
  };
}
