import React from 'react';
import Head from 'next/head';
import Row from '../../general-styles/Row';
import RowContainer from '../../general-styles/RowContainer';
import Img from '../../components/Image/Img';
import Image from 'next/image';
// import useDimensions from '../custom-design-hooks/useDimensions';

export default function Home() {
  // const width = useDimensions('resize');
  console.log('Inside home');
  return (
    <React.Fragment>
      <Head>
        <title>TWS Framework </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row color='#facf57'>
        <RowContainer displayOption='grid-center'>
          <div className='col-span-12 lg:col-span-6'>
            <h1>This is the about us page</h1>
          </div>
          <div className='col-span-12 lg:col-span-6 bg-red-800'>
            <Image
              src='https://source.unsplash.com/random/1800x900'
              width={1800}
              height={900}
            />
          </div>
        </RowContainer>
      </Row>
    </React.Fragment>
  );
}
