import React from 'react';
import Head from 'next/head';
import Row from '../general-styles/Row';
import RowContainer from '../general-styles/RowContainer';
import Typography from '../general-styles/Typography';

// import useDimensions from '../custom-design-hooks/useDimensions';

export default function Home() {
  // const width = useDimensions('resize');
  // console.log('Inside home');
  return (
    <React.Fragment>
      <Head>
        <title>TWS Framework </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Row color='#848587'>
        <RowContainer displayOption='grid-fit'>
          {/* <section> */}
          <div className='bg-red-500'>
            <Typography variant='h3'>Main content area</Typography>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit recusandae obcaecati sapiente
              aliquid. Eligendi, est harum eos laudantium quia optio. Asperiores
              nemo delectus quas earum consectetur!
            </p>
          </div>
        </RowContainer>
      </Row>

      <Row color='#facf57'>
        <RowContainer displayOption='grid'>
          <div className='col-span-1 bg-indigo-500 h-full'></div>

          <div className='w-[100%] col-span-10'>
            <h1>Main content area right column</h1>

            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti
              porro dolores accusantium odit
            </p>
          </div>
          <div className='col-span-1 bg-indigo-500 h-full'></div>
        </RowContainer>
      </Row>
    </React.Fragment>
  );
}
